version: "3.8"

services:
  mosquitto-bt:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-bt
    ports:
      - "1883:1883"
    volumes:
      - "./config/mosquitto:/mosquitto/config"
      - "./.data/mosquitto:/mosquitto/data"
    networks:
      - bt-network

  node-red-bt:
    image: nodered/node-red:latest
    container_name: node-red-bt
    ports:
      - "1880:1880"
    volumes:
      - "./.data/node-red:/data"
    networks:
      - bt-network

  chronograf-bt:
    container_name: chronograf-bt
    image: chronograf:latest
    ports:
      - '127.0.0.1:8888:8888'
    volumes:
      - "./.data/chronograf:/var/lib/chronograf"
    environment:
      - INFLUXDB_URL=http://influxdb-bt:8086
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME}
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - bt-network

  influxdb-bt:
    container_name: influxdb-bt
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - "./.data/influxdb:/var/lib/influxdb2"
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
    networks:
      - bt-network

  # mongodb-bt:
  #   container_name: mongodb-bt
  #   image: mongo:6.0
  #   volumes:
  #     - ./.data/mongodb:/data/db
  #   ports:
  #     - "27017:27017"
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=admin
  #     - MONGO_INITDB_ROOT_PASSWORD=admin
  #     - MONGO_INITDB_DATABASE=admin
  #   networks:
  #     - bt-network

  grafana-bt:
    container_name: grafana-bt
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./.data/grafana:/var/lib/grafana
      - ./.data/grafana-provisioning/:/etc/grafana/provisioning
      - ./.data/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    networks:
      - bt-network


networks:
  bt-network:
    driver: bridge
